# Generated by Django 3.2.6 on 2021-09-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='descripcion',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
